name: Publish to Dockerhub

on:
    push:
        branches:
            - "main"
        paths-ignore:
            - "**.md"
            - "LICENSE"
            - "LICENSE.txt"

jobs:
    dockerhub:
        name: Publish Docker Image(s) to Dockerhub
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_PASSWORD }}

            - name: Cache Docker layers naarad-ntfy
              uses: actions/cache@v3
              with:
                  path: /tmp/.buildx-cache-naarad-ntfy
                  key: ${{ runner.os }}-buildx-naarad-ntfy-${{ github.sha }}
                  restore-keys: |
                      ${{ runner.os }}-buildx-naarad-ntfy-

            - name: Build & Push naarad-ntfy
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: Dockerfile-build
                  push: true
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/naarad-ntfy:latest
                  cache-from: type=local,src=/tmp/.buildx-cache-naarad-ntfy
                  cache-to: type=local,dest=/tmp/.buildx-cache-naarad-ntfy-new,mode=max

            - name: Move naarad-ntfy cache
              run: |
                  rm -rf /tmp/.buildx-cache-naarad-ntfy
                  mv /tmp/.buildx-cache-naarad-ntfy-new /tmp/.buildx-cache-naarad-ntfy
